package com.mehta.model;

// Generated Feb 5, 2016 3:07:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cdr generated by hbm2java
 */
@Entity
@Table(name = "cdr", uniqueConstraints = @UniqueConstraint(columnNames = "audio_file_name"))
public class Cdr implements java.io.Serializable {

	private Integer id;
	private Date calldate;
	private String clid;
	private String src;
	private String dst;
	private String extn;
	private String dcontext;
	private String channel;
	private String dstchannel;
	private String lastapp;
	private String lastdata;
	private int duration;
	private int billsec;
	private String disposition;
	private int amaflags;
	private String accountcode;
	private String uniqueid;
	private String userfield;
	private String peeraccount;
	private String linkedid;
	private int sequence;
	private String audioFileName;
	private Integer inOutFlag;
	private Long createdByTaskId;


	public Cdr() {
	}
	public Cdr(Integer id) {
		this.id=id;
	}


	public Cdr(Date calldate, String clid, String src, String dst,String extn,
			String dcontext, String channel, String dstchannel, String lastapp,
			String lastdata, int duration, int billsec, String disposition,
			int amaflags, String accountcode, String uniqueid,
			String userfield, String peeraccount, String linkedid, int sequence, Integer inOutFlag) {
		this.calldate = calldate;
		this.clid = clid;
		this.src = src;
		this.dst = dst;
		this.extn =extn;
		this.dcontext = dcontext;
		this.channel = channel;
		this.dstchannel = dstchannel;
		this.lastapp = lastapp;
		this.lastdata = lastdata;
		this.duration = duration;
		this.billsec = billsec;
		this.disposition = disposition;
		this.amaflags = amaflags;
		this.accountcode = accountcode;
		this.uniqueid = uniqueid;
		this.userfield = userfield;
		this.peeraccount = peeraccount;
		this.linkedid = linkedid;
		this.sequence = sequence;
		this.inOutFlag = inOutFlag;

	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "calldate", nullable = false, length = 19)
	public Date getCalldate() {
		return calldate;
	}

	public void setCalldate(Date calldate) {
		this.calldate = calldate;
	}

	@Column(name = "clid", nullable = false, length = 80)
	public String getClid() {
		return clid;
	}

	public void setClid(String clid) {
		this.clid = clid;
	}

	@Column(name = "src", nullable = false, length = 80)
	public String getSrc() {
		return src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	@Column(name = "dst", nullable = false, length = 80)
	public String getDst() {
		return dst;
	}

	public void setDst(String dst) {
		this.dst = dst;
	}
	@Column(name = "extn")
	public String getExtn() {
		return extn;
	}
	public void setExtn(String extn) {
		this.extn = extn;
	}
	@Column(name = "dcontext", nullable = false, length = 80)
	public String getDcontext() {
		return dcontext;
	}

	public void setDcontext(String dcontext) {
		this.dcontext = dcontext;
	}

	@Column(name = "channel", nullable = false, length = 80)
	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "dstchannel", nullable = false, length = 80)
	public String getDstchannel() {
		return dstchannel;
	}

	public void setDstchannel(String dstchannel) {
		this.dstchannel = dstchannel;
	}

	@Column(name = "lastapp", nullable = false, length = 80)
	public String getLastapp() {
		return lastapp;
	}

	public void setLastapp(String lastapp) {
		this.lastapp = lastapp;
	}

	@Column(name = "lastdata", nullable = false, length = 80)
	public String getLastdata() {
		return lastdata;
	}

	public void setLastdata(String lastdata) {
		this.lastdata = lastdata;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "billsec", nullable = false)
	public int getBillsec() {
		return billsec;
	}

	public void setBillsec(int billsec) {
		this.billsec = billsec;
	}

	@Column(name = "disposition", nullable = false, length = 45)
	public String getDisposition() {
		return disposition;
	}

	public void setDisposition(String disposition) {
		this.disposition = disposition;
	}

	@Column(name = "amaflags", nullable = false)
	public int getAmaflags() {
		return amaflags;
	}

	public void setAmaflags(int amaflags) {
		this.amaflags = amaflags;
	}

	@Column(name = "accountcode", nullable = false, length = 20)
	public String getAccountcode() {
		return accountcode;
	}

	public void setAccountcode(String accountcode) {
		this.accountcode = accountcode;
	}

	@Column(name = "uniqueid", nullable = false, length = 32)
	public String getUniqueid() {
		return uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	@Column(name = "userfield", nullable = false)
	public String getUserfield() {
		return userfield;
	}

	public void setUserfield(String userfield) {
		this.userfield = userfield;
	}

	@Column(name = "peeraccount", nullable = false, length = 20)
	public String getPeeraccount() {
		return peeraccount;
	}

	public void setPeeraccount(String peeraccount) {
		this.peeraccount = peeraccount;
	}

	@Column(name = "linkedid", nullable = false, length = 32)
	public String getLinkedid() {
		return linkedid;
	}

	public void setLinkedid(String linkedid) {
		this.linkedid = linkedid;
	}

	@Column(name = "sequence", nullable = false)
	public int getSequence() {
		return sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	@Column(name = "audio_file_name", unique = true, length = 100)
	public String getAudioFileName() {
		return audioFileName;
	}

	public void setAudioFileName(String audioFileName) {
		this.audioFileName = audioFileName;
	}
	@Column(name="in_out_flag")
	public Integer getInOutFlag() {
		return inOutFlag;
	}
	public void setInOutFlag(Integer inOutFlag) {
		this.inOutFlag = inOutFlag;
	}
	@Column(name = "created_by_task_id")
	public Long getCreatedByTaskId() {
		return createdByTaskId;
	}

	public void setCreatedByTaskId(Long createdByTaskId) {
		this.createdByTaskId = createdByTaskId;
	}



}
